site_name: Roxwood County
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
    - toc.follow
    - content.action.edit
    - content.action.view
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16        
  language: nl
  palette:
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Overschakelen naar light mode    
      primary: custom
      accent: custom
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Overschakelen naar dark mode
      primary: custom
      accent: custom     
  favicon: img/logo.png
  logo: img/logo.webp    
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/
  generator: false    
copyright: |
  &copy; 2025 <a href="https://www.google.nl/"  target="_blank" rel="noopener">90s Roleplay</a>
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg    
nav:
  - Home: index.md  
  - Stadsbestuur: stadsbestuur.md
  - Department of Justice:
    - Uitleg DOJ: Department of Justice/doj.md
    - Rechtbank: Department of Justice/rechtbank.md
    - Sanctienormen: Department of Justice/sanctienormen.md
    - Vergunningen: Department of Justice/vergunningen.md
  - Wetgeving:    
    - Wetboek van Strafrecht: Wetgeving/sr.md
    - Wetboek van Strafvordering: Wetgeving/sv.md
    - Opiumwet: Wetgeving/opw.md
    - Wet wapens en munitie: Wetgeving/wwm.md
    - Wegenverkeerswet 1994: Wetgeving/wvw.md
    - Overig:
         - Wet gedeeltelijk verbod gezichtsbedekkende kleding: Wetgeving/Overig/wgvgk.md
         - Wet op de identificatieplicht: Wetgeving/Overig/wid.md
         - Algemene wet op het binnentreden: Wetgeving/Overig/awbi.md
  # - Politiewet 2012: polw2012.md
  # - Ambtsinstructie: ambts.md

extra_css:
  - stylesheets/extra.css
